peer:
  name: Peer1
  scraping-frequency-minutes: 30

media:
  types:
    video: mp4,mkv,avi
    audio: mp3,flac,aac,wmv

spring:
  datasource:
    url: jdbc:sqlite:your-database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update